# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DiversityFactor
                                 A QGIS plugin
 This plugin calculates the energy diveristy of buildings
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-14
        copyright            : (C) 2019 by Samuel Letellier-Duchesne
        email                : samuel.letellier-duchesne@polymtl.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DiversityFactor class from file DiversityFactor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .diversity_calc import DiversityFactor
    return DiversityFactor(iface)
